name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  apk:
    uses: QuestNav/QuestNav/.github/workflows/build-questnav-apk.yml@main
    with:
      versionMajor: 1
      versionMinor: 0
      versionPatch: 0
      versionYear: 2025
      versionType: 'dev'
    secrets:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

  lib:
    uses: QuestNav/QuestNav/.github/workflows/build-questnav-lib.yml@main
    with:
      versionMajor: 1
      versionMinor: 0
      versionPatch: 0
      versionYear: 2025
      versionType: 'dev'
      wpilibVersion: '2025.3.2'
      releaseToMaven: false
    secrets:
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
